#!/bin/sh

if [ "$1" = "clean" ]
then
	echo "Deleting executables :"
	rm -fv *.exe
	exit
fi

rm -fv test_driver.exe
rm -fv ~/encode_test_driver.exe
rm -fv encode_test_driver.exe

/home/thomas/polytech/projet_implementation/os/output/host/bin/arm-buildroot-linux-gnueabihf-gcc -static test_driver.c -o test_driver.exe
uuencode test_driver.exe decode_test_driver.exe > encode_test_driver.exe 
cp encode_test_driver.exe ~
